// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwzj464ed4fykEXKMFkjXGapYl5T6Pi14',
    appId: '1:445423561826:web:755d254a9c0499c943f53b',
    messagingSenderId: '445423561826',
    projectId: 'rv-fitness',
    authDomain: 'rv-fitness.firebaseapp.com',
    storageBucket: 'rv-fitness.firebasestorage.app',
    measurementId: 'G-TQCEK8KLBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHjFCQDU_YHJ610HbdulDdGnQan8MpuY',
    appId: '1:445423561826:android:01aa0b6ccdb0aed143f53b',
    messagingSenderId: '445423561826',
    projectId: 'rv-fitness',
    storageBucket: 'rv-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6P_joCBsd75m1DNqoMlw4WsonZBPjgcc',
    appId: '1:445423561826:ios:c28a07740c1cb06643f53b',
    messagingSenderId: '445423561826',
    projectId: 'rv-fitness',
    storageBucket: 'rv-fitness.firebasestorage.app',
    iosBundleId: 'com.example.rvFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6P_joCBsd75m1DNqoMlw4WsonZBPjgcc',
    appId: '1:445423561826:ios:c28a07740c1cb06643f53b',
    messagingSenderId: '445423561826',
    projectId: 'rv-fitness',
    storageBucket: 'rv-fitness.firebasestorage.app',
    iosBundleId: 'com.example.rvFitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwzj464ed4fykEXKMFkjXGapYl5T6Pi14',
    appId: '1:445423561826:web:ec2700f061fe71fe43f53b',
    messagingSenderId: '445423561826',
    projectId: 'rv-fitness',
    authDomain: 'rv-fitness.firebaseapp.com',
    storageBucket: 'rv-fitness.firebasestorage.app',
    measurementId: 'G-W456Q239F9',
  );
}
